version: '3.8'

# SSL-aware deployment with automatic HTTP fallback
# This version handles cases where SSL certificates cannot be created

services:
  # Nginx with enhanced SSL handling
  nginx:
    image: nginx:alpine
    container_name: dt-visuals-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro  # Template config
      - ./nginx-startup.sh:/nginx-startup.sh:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-certs:/etc/letsencrypt              # Writable volume for certificates
      - certbot-www:/var/www/certbot:ro
    environment:
      - NGINX_SSL_ENABLED=auto  # auto, true, false
    entrypoint: []
    command: ["sh", "/nginx-startup.sh"]
    depends_on:
      app-prod:
        condition: service_healthy
      app-dev:
        condition: service_healthy
    networks:
      - dt-visuals-network

  # Production App (unchanged)
  app-prod:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dtv:prod-latest
    container_name: dt-visuals-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://dtvisuals:${PROD_DB_PASSWORD}@db-prod:5432/dt_visuals_prod
      - SESSION_SECRET=${PROD_SESSION_SECRET}
      - DOCKER_ENV=true
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - uploads-prod:/app/uploads
    networks:
      - dt-visuals-network
    depends_on:
      db-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development App (unchanged)
  app-dev:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dtv:dev-latest
    container_name: dt-visuals-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dtvisuals:${DEV_DB_PASSWORD}@db-dev:5432/dt_visuals_dev
      - SESSION_SECRET=${DEV_SESSION_SECRET}
      - DOCKER_ENV=true
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - uploads-dev:/app/uploads
    networks:
      - dt-visuals-network
    depends_on:
      db-dev:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Production Database (unchanged)
  db-prod:
    image: postgres:15-alpine
    container_name: dt-visuals-db-prod
    restart: unless-stopped
    ports:
      - "0.0.0.0:5433:5432"
    environment:
      - POSTGRES_DB=dt_visuals_prod
      - POSTGRES_USER=dtvisuals
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - db-prod-data:/var/lib/postgresql/data
    networks:
      - dt-visuals-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dtvisuals -d dt_visuals_prod"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development Database (unchanged)
  db-dev:
    image: postgres:15-alpine
    container_name: dt-visuals-db-dev
    restart: unless-stopped
    ports:
      - "0.0.0.0:5434:5432"
    environment:
      - POSTGRES_DB=dt_visuals_dev
      - POSTGRES_USER=dtvisuals
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    networks:
      - dt-visuals-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dtvisuals -d dt_visuals_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  uploads-prod:
    driver: local
    name: dt-visuals-uploads-prod
  uploads-dev:
    driver: local
    name: dt-visuals-uploads-dev
  db-prod-data:
    driver: local
    name: dt-visuals-db-prod
  db-dev-data:
    driver: local
    name: dt-visuals-db-dev
  nginx-certs:
    driver: local
    name: dt-visuals-nginx-certs
  certbot-www:
    driver: local
  certbot-conf:
    driver: local

networks:
  dt-visuals-network:
    driver: bridge