# Development Environment - Docker Compose Configuration
version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: dt-visuals-dev
    ports:
      - "3000:5000"  # Different port for dev to avoid conflicts
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:${DEV_POSTGRES_PASSWORD:-devpassword}@postgres-dev:5432/${DEV_POSTGRES_DB:-dt_visuals_dev}
      - SESSION_SECRET=${DEV_SESSION_SECRET:-dev-session-secret-key}
      - PORT=5000
      - HOST=0.0.0.0
      - ENABLE_TIMELINE=true
      - VIDEO_UPLOAD_LIMIT=100MB
      - TIMELINE_NOTES_MAX_LENGTH=5000
    volumes:
      - .:/app
      - node-modules-dev:/app/node_modules  # Use named volume for node_modules
      - uploads-dev:/app/uploads
      - vite-cache-dev:/app/node_modules/.vite  # Dedicated volume for Vite cache
    depends_on:
      postgres-dev:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dt-visuals-dev
    command: npm run dev

  postgres-dev:
    image: postgres:15-alpine
    container_name: dt-visuals-postgres-dev
    environment:
      - POSTGRES_DB=${DEV_POSTGRES_DB:-dt_visuals_dev}
      - POSTGRES_USER=${DEV_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD:-devpassword}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./docker/postgres/init-dev.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5433:5432"  # Different port to avoid conflicts with production
    restart: unless-stopped
    networks:
      - dt-visuals-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_POSTGRES_USER:-postgres} -d ${DEV_POSTGRES_DB:-dt_visuals_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-dev-data:
    driver: local
    name: dt-visuals-postgres-dev-data
  uploads-dev:
    driver: local
    name: dt-visuals-uploads-dev  
  node-modules-dev:
    driver: local
    name: dt-visuals-node-modules-dev
  vite-cache-dev:
    driver: local
    name: dt-visuals-vite-cache-dev

networks:
  dt-visuals-dev:
    driver: bridge
    name: dt-visuals-dev-network