version: '3.8'

services:
  # Nginx reverse proxy for SNI routing
  nginx:
    image: nginx:alpine
    container_name: dt-visuals-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot-www:/var/www/certbot:ro
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - app-prod
      - app-dev

  # Production App
  app-prod:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dt-visuals:prod-latest
    container_name: dt-visuals-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${PROD_DATABASE_URL}
      - SESSION_SECRET=${PROD_SESSION_SECRET}
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - uploads-prod:/app/uploads
    networks:
      - dt-visuals-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development App
  app-dev:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dt-visuals:dev-latest
    container_name: dt-visuals-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DEV_DATABASE_URL}
      - SESSION_SECRET=${DEV_SESSION_SECRET}
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - uploads-dev:/app/uploads
    networks:
      - dt-visuals-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certbot for Let's Encrypt SSL
  certbot:
    image: certbot/certbot
    container_name: dt-visuals-certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${ACME_EMAIL} --agree-tos --no-eff-email -d dtvisuals.com -d dev.dtvisuals.com
    depends_on:
      - nginx

volumes:
  uploads-prod:
    driver: local
    name: dt-visuals-uploads-prod
  uploads-dev:
    driver: local
    name: dt-visuals-uploads-dev
  certbot-www:
    driver: local
  certbot-conf:
    driver: local

networks:
  dt-visuals-network:
    driver: bridge