# Traefik Static Configuration
api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: ${ACME_EMAIL}
      storage: /data/acme.json
      # Uncomment below for staging/testing (comment out for production)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# Optional: Configure metrics for monitoring
# metrics:
#   prometheus:
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5.0

# Optional: Configure logging
log:
  level: DEBUG

accessLog: {}

# Global middleware for security headers
http:
  middlewares:
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlAllowOriginList:
          - https://dtvisuals.com
          - https://dev.dtvisuals.com
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true